name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master

      - name: Installing project dependencies
        run: npm install
      - name: Prettier fix
        run: npm run lint --fix
      - name: Building the project
        run: npm run build
      - name: Echo back
        run: echo Build done
  run:
      runs-on: ubuntu-latest
      needs: build
      steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - name: Test run
        run: npm start