name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - name: Installing project dependencies
        run: npm install
      - name: Prettier fix
        run: npm run lint --fix
      - name: Building the project
        run: npm run build
  run-linux:
    runs-on: ubuntu-latest
    needs: build-linux
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - name: Test run
        run: npm start
  archive-dist:
    runs-on: ubuntu-latest
    needs: build-linux
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist
